services:
  valkey: # Changed from redis to valkey
    image: "valkey/valkey"
    container_name: transcoder-valkey
    ports:
      - "6379:6379" # Valkey uses the same default port as Redis
    volumes:
      - valkey_data:/data # Persist Valkey data
    command: valkey-server --appendonly yes # Enable AOF persistence (same command structure)

  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port (web UI)
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin # Replace with your desired access key
      MINIO_ROOT_PASSWORD: minioadmin # Replace with your desired secret key
      MINIO_DEFAULT_BUCKETS: "input-videos,output-videos" # Create these buckets on startup
    command: server /data --console-address ":9001"
    healthcheck: # Optional: useful to know when MinIO is ready
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

volumes:
  valkey_data:
  minio_data: